In [29]:
import os
path = os.path.join('..','data')
os.makedirs(path,exist_ok=True)
data_file = os.path.join(path,'house_z.csv')
with open(data_file,'w')as file:
    file.write('NumRooms,Alley,HouseAge,Garage,Area,Price\n')
    file.write('NA,Pave,10,NA,85,127500\n')
    file.write('2,NA,15,NA,70,106000\n')
    file.write('4,Grvl,NA,Yes,120,178100\n')
    file.write('NA,NA,20,NA,95,140000\n')
    file.write('3,Pave,12,NA,105,160000\n')
    file.write('5,Grvl,8,No,150,210000\n')
    file.write('2,NA,18,NA,80,135000\n')
    file.write('4,Pave,25,NA,130,190000\n')
    file.write('3,Grvl,NA,NA,110,165000\n')

In [30]:
import pandas as pd
data = pd.read_csv(data_file)
data

   NumRooms Alley  HouseAge Garage  Area   Price
0       NaN  Pave      10.0    NaN    85  127500
1       2.0   NaN      15.0    NaN    70  106000
2       4.0  Grvl       NaN    Yes   120  178100
3       NaN   NaN      20.0    NaN    95  140000
4       3.0  Pave      12.0    NaN   105  160000
5       5.0  Grvl       8.0     No   150  210000
6       2.0   NaN      18.0    NaN    80  135000
7       4.0  Pave      25.0    NaN   130  190000
8       3.0  Grvl       NaN    NaN   110  165000

In [31]:
inputs,outputs = data.iloc[:,0:5],data.iloc[:,5]
display(inputs)
display(outputs)

   NumRooms Alley  HouseAge Garage  Area
0       NaN  Pave      10.0    NaN    85
1       2.0   NaN      15.0    NaN    70
2       4.0  Grvl       NaN    Yes   120
3       NaN   NaN      20.0    NaN    95
4       3.0  Pave      12.0    NaN   105
5       5.0  Grvl       8.0     No   150
6       2.0   NaN      18.0    NaN    80
7       4.0  Pave      25.0    NaN   130
8       3.0  Grvl       NaN    NaN   110

0    127500
1    106000
2    178100
3    140000
4    160000
5    210000
6    135000
7    190000
8    165000
Name: Price, dtype: int64

In [32]:
def drop_col(m):
    col = m.isna().sum().idxmax()
    m = m.drop(columns = [col])
    return m
inputs = drop_col(inputs)
display(inputs)
display(outputs)

   NumRooms Alley  HouseAge  Area
0       NaN  Pave      10.0    85
1       2.0   NaN      15.0    70
2       4.0  Grvl       NaN   120
3       NaN   NaN      20.0    95
4       3.0  Pave      12.0   105
5       5.0  Grvl       8.0   150
6       2.0   NaN      18.0    80
7       4.0  Pave      25.0   130
8       3.0  Grvl       NaN   110

0    127500
1    106000
2    178100
3    140000
4    160000
5    210000
6    135000
7    190000
8    165000
Name: Price, dtype: int64

In [33]:
inputs = inputs.fillna(inputs.mean(numeric_only=True))
display(inputs)

   NumRooms Alley   HouseAge  Area
0  3.285714  Pave  10.000000    85
1  2.000000   NaN  15.000000    70
2  4.000000  Grvl  15.428571   120
3  3.285714   NaN  20.000000    95
4  3.000000  Pave  12.000000   105
5  5.000000  Grvl   8.000000   150
6  2.000000   NaN  18.000000    80
7  4.000000  Pave  25.000000   130
8  3.000000  Grvl  15.428571   110

In [34]:
inputs = pd.get_dummies(inputs,columns = ['Alley'],dummy_na=True,dtype = int)
display(inputs)

   NumRooms   HouseAge  Area  Alley_Grvl  Alley_Pave  Alley_nan
0  3.285714  10.000000    85           0           1          0
1  2.000000  15.000000    70           0           0          1
2  4.000000  15.428571   120           1           0          0
3  3.285714  20.000000    95           0           0          1
4  3.000000  12.000000   105           0           1          0
5  5.000000   8.000000   150           1           0          0
6  2.000000  18.000000    80           0           0          1
7  4.000000  25.000000   130           0           1          0
8  3.000000  15.428571   110           1           0          0

In [41]:
import torch
x,y = torch.tensor(inputs.to_numpy(dtype='float32')),torch.tensor(outputs.to_numpy(dtype='float32'))
print('inputs:','\n',x)
print('outputs:','\n',y)

inputs:
 tensor([[  3.2857,  10.0000,  85.0000,   0.0000,   1.0000,   0.0000],
        [  2.0000,  15.0000,  70.0000,   0.0000,   0.0000,   1.0000],
        [  4.0000,  15.4286, 120.0000,   1.0000,   0.0000,   0.0000],
        [  3.2857,  20.0000,  95.0000,   0.0000,   0.0000,   1.0000],
        [  3.0000,  12.0000, 105.0000,   0.0000,   1.0000,   0.0000],
        [  5.0000,   8.0000, 150.0000,   1.0000,   0.0000,   0.0000],
        [  2.0000,  18.0000,  80.0000,   0.0000,   0.0000,   1.0000],
        [  4.0000,  25.0000, 130.0000,   0.0000,   1.0000,   0.0000],
        [  3.0000,  15.4286, 110.0000,   1.0000,   0.0000,   0.0000]])
outputs:
 tensor([127500., 106000., 178100., 140000., 160000., 210000., 135000., 190000.,
        165000.])